services:
  web:
    build: .
    working_dir: /data
    command: python frameac2.py
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "5005:5005"

  db:	
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: 12345666
    ports:
      - "3306:3306"
